### ISSUE TITLE
Looks like Mozilla break it again

### ISSUE THREAD

**Issue by 117649** [p1usminus/roomybookmarksredux#11]
@p1usminus 
Now refresh a page or open a new page would cause booksmarks bar be expanded while **auto hide booksmarks bar** is enabled even without meet proper trigger requirement.

**Comment by 117649** [comment]
OK. 
It seems because I'm using a new profile thus not set **browser.toolbars.bookmarks.2h2020** to false.
May be we should make it a check box and set it default to false in this extension's option window.

**Comment by p1usminus** [comment]
Okay, I'm glad this is nothing major 😀 

I was trying to avoid changing user's preferences (outside of the addon's prefs) but including a check box sounds like a good idea. I will try it later today.
