### ISSUE TITLE
This time a real problem

### ISSUE THREAD

**Issue by 117649** [p1usminus/roomybookmarksredux#12]
Its happened to me that after a while context menu on booksmarks bar stop working.
Both the context menu for the bar and booksmark item just won't display after right click.
Don't have a clue for the reason yet.

**Comment by 117649** [comment]
I've got it. If the bar is collapsed then there is a chance it been uninitiated.
Thus I've add code to ensure it is initiated when it is expanded: https://github.com/p1usminus/roomybookmarksredux/pull/13
Can you test this? @p1usminus

**Comment by p1usminus** [comment]
Yes! Testing it now 😊

**Comment by p1usminus** [comment]
Okay, it looks like this fixes this problem:
> * Sometimes the toolbar simply breaks - such as when disabling the multirow option (while using the auto-hide feature).

which is brilliant!

I saw this error a few times:
![image](https://user-images.githubusercontent.com/50540305/130361534-ad6877f5-7099-43e7-94f9-8a96bc387570.png)

I think it happens when clicking or creating a folder on the toolbar (or the chevron if the window is too small) - it appears once when clicking each folder.

But I am not sure _why_ it appears. The options that relate to the individual bookmark items still work fine.

**Comment by 117649** [comment]
> I saw this error a few times:
> ![image](https://user-images.githubusercontent.com/50540305/130361534-ad6877f5-7099-43e7-94f9-8a96bc387570.png)
> 
> I think it happens when clicking or creating a folder on the toolbar (or the chevron if the window is too small) - it appears once when clicking each folder.
> 
> But I am not sure _why_ it appears. The options that relate to the individual bookmark items still work fine.

This seems totally OK.
That line is checking **node.classList** if the **node**  don't even have a **classList** it should just fail.
Just ~add missing condition expression `node.classList && node.classList.contains("bookmark-item")` or~ simply use [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) `node.classList?.contains("bookmark-item")` to eliminate the error it should be just fine.

**Comment by p1usminus** [comment]
> use the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) `node.classList?.contains("bookmark-item")` to eliminate the error it should be just fine.

That is beautiful, thank you!

I was going to save this for a later update but I changed a couple of other things so will include it in the next commit.
