### ISSUE TITLE
Did you manage to enable auto-update

### ISSUE THREAD

**Issue by onemen** [p1usminus/roomybookmarksredux#14]
Did you manage to enable auto update and/or check for update from about:addons ?

**Comment by 117649** [comment]
Installed 1.7.3 again and set auto update off then click **Check fo Updates**
![image](https://user-images.githubusercontent.com/8281345/134360378-e9921b93-6181-44d3-aa14-3cc43de272c4.png)
![image](https://user-images.githubusercontent.com/8281345/134360684-36c10a9f-8fa3-4fe0-b87d-b1deb801c4d0.png)

Results:
![image](https://user-images.githubusercontent.com/8281345/134360485-0dbb7a5b-3c0a-47a6-99a1-f365702fa2ec.png)
![image](https://user-images.githubusercontent.com/8281345/134360555-0b39cdff-4a19-41c9-b4c3-9985f04e5627.png)

**Comment by onemen** [comment]
I have a problem, I can't update any extension

Using New profile on Firefox 92.0, windows 10

when trying to update nothing happened and I see this messages in the error console/
```
1632322553616	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/p1usminus/roomybookmarksredux/master/update.json - [Exception... "Certificate issuer is not built-in."  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 183"  data: no]
1632322553630	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/onemen/TabMixPlus/main/config/updates-dev-build.json - [Exception... "Certificate issuer is not built-in."  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 183"  data: no]
```

**Comment by 117649** [comment]
Well I've tested on 93b07 dev ed may that's the problem.

**Comment by 117649** [comment]
And no, just successes on 92:
![图片](https://user-images.githubusercontent.com/8281345/134374895-78dc8cc5-17f4-455c-b1f6-1c2bb9d5c3a7.png)
 @onemen may be there is some problem with your Certs as it states.

**Comment by onemen** [comment]
It look like an issue with my antivirus ESET
![Certificate](https://user-images.githubusercontent.com/3650909/134376205-19d46f51-b63c-46c3-88ad-95dadecb5ef2.png)

**Comment by onemen** [comment]
ESET add locked pref:
```pref("security.enterprise_roots.enabled", true, locked);```
when i remove this pref i get the update working ok

**Comment by onemen** [comment]
since "security.enterprise_roots.enabled" is locked by ESET, i'v changed the preference ```extensions.update.requireBuiltInCerts``` to false

**Comment by p1usminus** [comment]
Sorry, I think I need to change my notification settings because I only saw this a few days ago and I wasn't sure what to say 😱 

I wondered if I should have Roomy change those last two prefs, but _maybe_ not since they are related to security. I could add a note about them to the readme? 😁

**Comment by onemen** [comment]
> I wondered if I should have Roomy change those last two prefs, but _maybe_ not since they are related to security.

Yes, I don't think we should recommend users to change these preferences
