### ISSUE TITLE
browser.toolbars.bookmarks.2h2020 is gone

### ISSUE THREAD

**Issue by p1usminus** [p1usminus/roomybookmarksredux#16]
As of FF 95.0b3. I knew this day would come. Roomy's autohide is now (sort of) broken.

When setting a new option for the Bookmarks Toolbar visibility in the context menu it takes precedence over Roomy in the first window, but Roomy seems to kick in in further/secondary windows.

I believe this is the pertinent function: https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#6674

Setting `browser.toolbars.bookmarks.visibility` to a non-standard value (such as roomy) seems to get things working as expected again in secondary windows but the toolbar is still erratic in the first window.

**Comment by p1usminus** [comment]
https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#5420

I think this is relevant as the toolbar reappears on every tab change

**Comment by 117649** [comment]
Just got mine dev ver bump to 95.0b3. 
Didn't change any setting yet.
Auto hide is working for me, It seem to me that what has changed is only the behavior while switch tabs.

**Comment by 117649** [comment]
> 
> 
> https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#5420
> 
> I think this is relevant as the toolbar reappears on every tab change

I don't have much time working on this.
But I think an easy way to solve this is to add a listener on 'TabSelect' event and let it force the bar to previous state.

**Comment by p1usminus** [comment]
thank you, I'll try!

**Comment by 117649** [comment]
> 
> 
> Okay, I think I have fixed it - though [my solution](https://github.com/p1usminus/roomybookmarksredux/commit/8d45f33cfefd5da2907863912f099707154a0481) feels kludgy 😅
> 
> When I tried to use an addEventListener it would only trigger on every new window, so I used a progress listener, similar to what is happening within here:
> 
> > https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#5420

@p1usminus 

Now the BB is force collapse after every tab switch. I was suggest that you use a variable to save the state of the bar and restore it after tab switch.

**Comment by p1usminus** [comment]
I think the behaviour has changed again in 95.0b4. I can no longer get any console logs from the progress listener and if I comment out the addProgressListener I added to startUpMainCheck the behaviour is the same. I have just tried the previous version of Roomy (v1.7.4) and the force collapse happens with this too!

**Comment by p1usminus** [comment]
> 
> 
> ~I think the behaviour has changed again in 95.0b4. I can no longer get any console logs from the progress listener and if I comment out the addProgressListener I added to startUpMainCheck the behaviour is the same. I have just tried the previous version of Roomy (v1.7.4) and the force collapse happens with this too!~

This actually happened again with 95.0b4 even after I had updated Roomy, but stopped after updating to b5 (on Windows) so there may have been some kind of issue but it's gone now.
