### ISSUE TITLE
Options menu & dark themes

### ISSUE THREAD

**Issue by p1usminus** [p1usminus/roomybookmarksredux#17]
It appears that when a dark theme is used the text in the options menu is changed to white. I will leave this for a while because it's quite strange and I have no ideas lol (perhaps it is a Firefox bug or related to Colorways? idk)

![image](https://user-images.githubusercontent.com/50540305/140804443-42c9d39f-ff34-4951-81f4-49100d38e8dc.png)

**Comment by p1usminus** [comment]
It is working fine in my Ubuntu VM. Maybe it is just a problem with my custom Windows theme 😬

**Comment by 117649** [comment]
@p1usminus 
This can be fixed very simply by adding a css style sheet reference:
```xml
<?xml-stylesheet href="chrome://global/skin/in-content/common.css" type="text/css"?>
```
Just at here:
https://github.com/p1usminus/roomybookmarksredux/blob/5b18add03f7c2fe4a013b04e604c90668031065b/src/content/options.xhtml#L2

Result:
![image](https://user-images.githubusercontent.com/8281345/155142522-7f462364-d023-428b-811c-4fe037c7253c.png)

**Comment by p1usminus** [comment]
> @p1usminus This can be fixed very simply by adding a css style sheet reference:
> 
> ```
> <?xml-stylesheet href="chrome://global/skin/in-content/common.css" type="text/css"?>
> ```

Unbelievable - such a simple fix 😅! It was bugging me so much because it was behaving as expected in Ubuntu and macOS. I thought I would just have to live with this on Windows.

Thank you!
