### ISSUE TITLE
Fx 108 "display booksmarks bar over page" not diaplay the bar over page but over everything.

### ISSUE THREAD

**Issue by 117649** [p1usminus/roomybookmarksredux#20]
If "display booksmarks bar over page" is checked it will display over tab bar at the top of the window.

Looks like some css fix are needed.

**Comment by 117649** [comment]
This can be fixed by set a negative `margin-bottom`.

**Comment by p1usminus** [comment]
Thanks for the tip, I will try fixing this later today!

I compared overPage.css with [this](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_toolbar.css) but I do not think this issue can be fixed with CSS alone 😢

Thinking out loud... I think I will have to change to overlay.js to find the height of #navigator-toolbox and then set `margin-bottom` to the negative of this value, as you suggested.

**Comment by 117649** [comment]
> Thinking out loud... I think I will have to change overlay.js to find the height of #navigator-toolbox and then set `margin-bottom` to the negative of this value, as you suggested.

Actually tried that route. However how do you find the height while the booksmark bar is auto hide(collapsed)?

Then back to a css fix:https://github.com/p1usminus/roomybookmarksredux/pull/21.

But this need more testing for compatibility.

**Comment by p1usminus** [comment]
> Then back to a css fix:#21.
> 
> But this need more testing for compatibility.

This is working nicely 👌🏾  thanks (I have only tested on Ubuntu so far)

But it breaks the feature in Waterfox G5 (I think it is based on Fx 102 ESR) so I could set a new minimum version with the next update.

> Actually tried that route. However how do you find the height while the booksmark bar is auto hide(collapsed)?
> 
I also tried modifying overlay.js in [another branch](https://github.com/p1usminus/roomybookmarksredux/commit/45d44c52540dc39f80f1f6655ee7a379e83657ed) and it works _okay_, but on startup the bookmarks bar is briefly displayed over the tab bar before it moves down! 🤔

**Comment by 117649** [comment]
> I also tried modifying overlay.js in [another branch](https://github.com/p1usminus/roomybookmarksredux/commit/45d44c52540dc39f80f1f6655ee7a379e83657ed) and it works _okay_, but on startup the bookmarks bar is briefly displayed over the tab bar before it moves down! 🤔

That is expected since we are waiting for booksmark bar is ready during startup.

> But it breaks the feature in Waterfox G5 (I think it is based on Fx 102 ESR) so I could set a new minimum version with the next update.

Its more likely because WF use a customized theme.

**Comment by 117649** [comment]
> I also tried modifying overlay.js in [another branch](https://github.com/p1usminus/roomybookmarksredux/commit/45d44c52540dc39f80f1f6655ee7a379e83657ed) and it works _okay_, but on startup the bookmarks bar is briefly displayed over the tab bar before it moves down! 🤔

If you want to go down that route I'd suggest set a css [variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) on `navigator-toolbox` then use it in overPage.css for `top:` (`position:` need to be `fixed`).

Also set up a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to update that variable.

**Comment by p1usminus** [comment]
I have _finally_ let my Windows install upgrade to 108 (and updated userChromeJS) to test the fixed version, the CSS fix is working 

I also saw [this](https://old.reddit.com/r/FirefoxCSS/comments/yyygzs/top_row_of_multirow_bookmark_bar_randomly_breaks/) last night, so I have modified `multirowBar.css` too.

It seems like there was a big change to userChrome.css with this version of Firefox, so I am okay with updating the strict_min_version.

> If you want to go down that route I'd suggest set a css [variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) or a HTML attribute on `navigator-toolbox` then use it in overPage.css for `top:` (`position:` need to be `fixed`).
> 
> You also need to set up a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to update that variable.

Interesting, but this seems like a major modification to fix one thing 😅

**Comment by 117649** [comment]
> Interesting, but this seems like a major modification to fix one thing 😅

It basically same as https://github.com/p1usminus/roomybookmarksredux/commit/45d44c52540dc39f80f1f6655ee7a379e83657ed. But more formally.
