### ISSUE TITLE
Autohide: bookmark items get lost in overflow if window is resized while bookmarks bar is collapsed

### ISSUE THREAD

**Issue by p1usminus** [p1usminus/roomybookmarksredux#23]
This one was hard to find lol - it only happens when the bookmark items are longer than the width of the resized window

Initial thoughts:
* I _think_ the issue lies with `#PlacesToolbarItems`
* It does not happen when using the multirow feature, which suggests this can also be fixed by CSS - perhaps I can copy/move something from `multirowBar.css` to `main.css` (otherwise I may have to try using a ResizeObserver 😨)

**Comment by 117649** [comment]
What is this I've tried myself open a new window and resized it while bookmarks bar is collapsed but nothing seems wrong.

Can you post some image?

**Comment by p1usminus** [comment]
Interesting, it is happening to me in Windows as well as Ubuntu & macOS VMs (in macOS I updated Firefox and Roomy but not userChrome.js to see if this would make a difference - the problem still appeared!)

![image](https://user-images.githubusercontent.com/50540305/203541170-2ec0667b-bcfd-4505-bd06-2b2c22e4c2bd.png)

![image](https://user-images.githubusercontent.com/50540305/203543116-3dffccce-4291-4ee1-8d6d-507878f01af9.png)

(It fixes itself if you resize again with the bookmarks bar visible, but I think I can fix it properly with a CSS tweak - I will try later)

**Comment by 117649** [comment]
OK, I see. Can reproduce on 108. 107 is not affected.

**Comment by 117649** [comment]
@p1usminus maybe try compare computed css rules between 107 and 108?

**Comment by 117649** [comment]
@p1usminus Last resort: through this piece somewhere 
```css

#PersonalToolbar[collapsed="true"] #personal-bookmarks{
	visibility: hidden;
}

```

But I have no ideal what else it will affect.

**Comment by p1usminus** [comment]
> @p1usminus maybe try compare computed css rules between 107 and 108?

Yes! 🚀 

I found these new rules in Fx108, but not Waterfox:

`[flex="1"] {
	-moz-box-flex: 1 !important;
}` <- applies to #PlacesToolbarItems (and #personal-bookmarks)

`#personal-bookmarks, #PlacesToolbar, #PlacesToolbarItems {
	min-width: 0;
}`

I feel like this has something to do with flex-wrap (if the default is nowrap and the list of bookmark items is considered too long by the browser, that may be why it puts them all in the overflow box). And it does not happen when multirow is used. I will copy the rule from [here](https://github.com/p1usminus/roomybookmarksredux/blob/master/src/skin/css/multirowBar.css#L14) now to see if it does anything

**Comment by 117649** [comment]
> > @p1usminus maybe try compare computed css rules between 107 and 108?
> 
> Yes! 🚀
> 
> I found these new rules in Fx108, but not Waterfox:
> 
> `[flex="1"] { -moz-box-flex: 1 !important; }` <- applies to #PlacesToolbarItems (and #personal-bookmarks)
> 
> `#personal-bookmarks, #PlacesToolbar, #PlacesToolbarItems { min-width: 0; }`
> 
> I feel like this has something to do with flex-wrap (if the default is nowrap and the list of bookmark items is considered too long by the browser, that may be why it puts them all in the overflow box). And it does not happen when multirow is used. I will copy the rule from [here](https://github.com/p1usminus/roomybookmarksredux/blob/master/src/skin/css/multirowBar.css#L14) now to see if it does anything
> 
> Okay it seems obvious now but setting `flex-wrap: wrap;` is what puts the bookmark items on multiple rows 😅 it prevents this overflow issue but then I cannot get them back to one row

I've found that the booksmarks bar generate way less overflow event when resizing window.
That maybe the one major fact of the cause.

**Comment by 117649** [comment]
I'm pretty sure lower event rate on `collapsed` element on 108 is the main reason now.
Manually dispatch 'overflow' and 'underflow' after booksmark bar show can fix the layout of the booksmark bar.
But you have to figure out which event is the real state of the bar to properly show/hide the chevron.

Change how the bar is hide seems most easy fix now:https://github.com/p1usminus/roomybookmarksredux/issues/23#issuecomment-1326021177

**Comment by 117649** [comment]
em, Add `PlacesToolbarHelper._viewElt._placesView._updateNodesVisibilityTimerCallback() ` into `roomybookmarkstoolbar.hideBookmarksBar` also has some good effect.

You can try each method and tell which has the best result.

**Comment by 117649** [comment]
```css
#PlacesToolbar {
	display: flex;
}

#PlacesToolbarItems {
	display: flex;
	margin-left: auto !important;
	margin-right: auto !important;
}

#PlacesToolbarItems *{
  flex-shrink: 0;
}
```

For fix bar overflow when items align to center.

**Comment by p1usminus** [comment]
14 days already 😬 

Sorry, I have been dealing with so many broken things lately. I hope I can come back to this this weekend!

**Comment by 117649** [comment]
And 23 days more.
@p1usminus Make sure you tested this: #24

**Comment by p1usminus** [comment]
> And 23 days more. @p1usminus Make sure you tested this: #24

I know, sorry 😓 

Thank you for the PR 🚀 , I will test it now

> I'm pretty sure lower event rate on `collapsed` element on 108 is the main reason now. Manually dispatch 'overflow' and 'underflow' after booksmark bar can fix the layout of the booksmark bar. But you have to figure out which event is the real state of the bar to properly show/hide the chevron.

How did you even find this?! 

> em, Add `PlacesToolbarHelper._viewElt._placesView._updateNodesVisibilityTimerCallback() ` into `roomybookmarkstoolbar.hideBookmarksBar` also has some good effect.

And this? It seems like such an obscure function. Interesting 🤔

**Comment by 117649** [comment]
> How did you even find this?!
> 
> > em, Add `PlacesToolbarHelper._viewElt._placesView._updateNodesVisibilityTimerCallback() ` into `roomybookmarkstoolbar.hideBookmarksBar` also has some good effect.
> 
> And this? It seems like such an obscure function. Interesting 🤔

Good old filed test.
But the real mechanic behind the scene still a mystery.

**Comment by p1usminus** [comment]
The CSS fix works well (the use of @supports is brilliant) along with this
> `PlacesToolbarHelper._viewElt._placesView._updateNodesVisibilityTimerCallback()`

but I was having an issue with some of the bookmark items appearing after mousing over the bookmarks bar after adding this function - it's hard for me to explain! - I wanted to record it but it has stopped now.

I have been looking at [browserPlacesViews.js](https://searchfox.org/mozilla-central/source/browser/components/places/content/browserPlacesViews.js#1242) and I'm trying `PlacesToolbarHelper._viewElt._placesView.updateNodesVisibility()` now - this also seems to work. Sometimes there is a tiny delay when updating the visibility of the items, but that's okay

I _think_ this is fixed now 😀

**Comment by p1usminus** [comment]
> but I was having an issue with some of the bookmark items appearing after mousing over the bookmarks bar after adding this function - it's hard for me to explain! - I wanted to record it but it has stopped now.

Got it - it happens after disabling multirow

[delayed visibility.webm](https://user-images.githubusercontent.com/50540305/210484718-3630f96e-2172-456a-954f-d22c278fb7fe.webm)

**Comment by 117649** [comment]
> ```css
> #PlacesToolbar {
> 	display: flex;
> }
> 
> #PlacesToolbarItems {
> 	display: flex;
> 	margin-left: auto !important;
> 	margin-right: auto !important;
> }
> 
> #PlacesToolbarItems *{
>   flex-shrink: 0;
> }
> ```
> 
> For fix bar overflow when items align to center.
@p1usminus We should revert this now since 
```css
#PlacesToolbarItems {-moz-box-pack: center}
```
start working again and the work around is not flawless.

**Comment by p1usminus** [comment]
> 
> ```css
> #PlacesToolbarItems {-moz-box-pack: center}
> ```
> 
> start working again and the work around is not flawless.
Thank you! I just updated to 111 so I can revert and test now

I also reopened this issue because I could see errors in the Browser Toolbox about
> 
>  `PlacesToolbarHelper._viewElt._placesView.updateNodesVisibility()` now - this also seems to work
> 
so I will probably have to remove it.

**Comment by p1usminus** [comment]
I think I messed up the revert commits so I made a new branch to work on this.

Using this again:
```
#PlacesToolbarItems {-moz-box-pack: center}
```
works fairly well, but when there are too many bookmark items there is 'overflow' on both sides!

![Screenshot from 2023-03-14 19-11-16](https://user-images.githubusercontent.com/50540305/225114163-13c27e45-f224-4776-a398-f2db2c150406.png)

I hope I can resolve this by setting the width of... ```#PlacesToolbar``` to 100vw in location-1/location-2.css like in multirowBar.css (or ```#PlacesToolbarItems``` itself). Testing now (my browser in Ubuntu has just updated to 112.0b1 and I can see another annoying change 😓 )!

**Comment by p1usminus** [comment]
The width of ```#personal-bookmarks, #PlacesToolbar, #PlacesToolbarItems``` looks fine upon inspection, it is just that the list of bookmark items is... too long for the box lol.

I will close this and try to unlock multirow for centre/right alignment so people have the option, to avoid this scenario.
