### ISSUE TITLE
overpage/multirow: bookmark items look different after disabling multirow

### ISSUE THREAD

**Issue by p1usminus** [p1usminus/roomybookmarksredux#25]
This one is really minor but I may come back to it when the other issues are closed.

When using the multirow and display over page options, if multirow is disabled the alignment of the bookmark items gets messed up - it's like the toolbar is the wrong height and the icons move like they are buttons (and are smaller.)

Before:
![Screenshot from 2023-01-04 04-07-57](https://user-images.githubusercontent.com/50540305/210484505-cf52f835-ab26-49ba-8489-8dafe00a21d4.png)

After:
![Screenshot from 2023-01-04 04-09-38](https://user-images.githubusercontent.com/50540305/210484536-7a631db8-4ab8-4f6f-b050-059a2bf73963.png)

After, mouseover
![Screenshot from 2023-01-04 04-09-56](https://user-images.githubusercontent.com/50540305/210484559-1e3efa65-f1f7-42ff-90dc-03ff193cfa42.png)

I initially thought it could be related to overPage.css, but given the behaviour shown [here](https://github.com/p1usminus/roomybookmarksredux/issues/23#issuecomment-1370476483), it may be related to the way the multirow feature is disabled in [overlay.js](https://github.com/p1usminus/roomybookmarksredux/blob/master/src/content/overlay.js#L382). Maybe it needs a ResizeObserver due to the (potential) height change of the bookmarks bar?

**Comment by p1usminus** [comment]
Okay so it looks like this only affects folders, weird.

Increasing the top/bottom margin (under 'Labels settings') cuts off more of the text and makes the folder icon smaller.

![Screenshot from 2023-01-04 05-06-04](https://user-images.githubusercontent.com/50540305/210488307-9b246be9-7ba3-48df-9f8b-5176a1556942.png)

**Comment by 117649** [comment]
> Okay so it looks like this only affects folders, weird.
> 
> Increasing the top/bottom margin (under 'Labels settings') cuts off more of the text and makes the folder icon smaller.
> 
> ![Screenshot from 2023-01-04 05-06-04](https://user-images.githubusercontent.com/50540305/210488307-9b246be9-7ba3-48df-9f8b-5176a1556942.png)

It's very understandable that folder have whole set of different padding/margin rules.

**Comment by p1usminus** [comment]
This is actually really annoying me! 

Computed rules have not given me anything useful.

It looks like the folder icon height is calculated from the `toolbar height - (top margin + bottom margin)`, instead of the toolbar height being calculated from `icon height + (top margin + bottom margin)`

And I am not sure what happened to the toolbarbutton-text, perhaps the wrong display type.

**Comment by p1usminus** [comment]
This was simply a padding conflict: https://old.reddit.com/r/FirefoxCSS/comments/10gtj8g/help_please_the_bookmark_bar_gets_worse_every/j56d1yv/
