### ISSUE TITLE
Options dialog window is slightly smaller than content

### ISSUE THREAD

**Issue by p1usminus** [p1usminus/roomybookmarksredux#27]
This is a really small issue but I have been trying to resolve it for the last few hours with no progress, so I will leave this here.

The options dialog window cuts off a few pixels on the right hand side of the options when opened:
![Screenshot from 2023-05-24 07-54-46](https://github.com/p1usminus/roomybookmarksredux/assets/50540305/ed7eec24-9295-4b8e-aaf4-da8b914e8dfd)

The window can be resized in Ubuntu but not Windows (10) to show everything.
![Screenshot from 2023-05-24 07-55-35](https://github.com/p1usminus/roomybookmarksredux/assets/50540305/15b62b98-1d6a-4fde-b911-027bb47179b6)

I have tried changing the widths of various elements (some of the attempts are commented out in `options.css`) but nothing I tried worked. I think it may be something to do with how the dialog window is created, but that is managed by the [BootStrapLoader](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/utils/BootstrapLoader.jsm#L26)

So instead I removed the border CSS from most of the fieldsets - they are virtually invisible with the dark theme 
![Screenshot from 2023-05-24 07-58-13](https://github.com/p1usminus/roomybookmarksredux/assets/50540305/00f3e03b-0d45-4f45-b121-6fbc7f469b0b)

**Comment by 117649** [comment]
I don't have this problem on win 10 with 113.
But I do remember there is some argument you can pass in for the size of the option dialog.
I think you can try check how TMP handle this.

**Comment by p1usminus** [comment]
> I don't have this problem on win 10 with 113. 

Interesting. I cannot think of a reason why this would be happening to me. 🤔 (I am currently on 114.0b8 but I think this has been happening to me for some time.)

> But I do remember there is some argument you can pass in for the size of the option dialog. I think you can try check how TMP handle this.

Yesss this is what I needed, thank you! [minwidth](https://github.com/onemen/TabMixPlus/blob/41b7f3360e3b58b863e91a8ef06bf5f14eb8e718/addon/chrome/content/preferences/preferences.xhtml#LL29C13-L29C13) did not work, but width did. I have set it so it is wide enough for Ubuntu (and hopefully macOS but I can check that later) and there is plenty of space on Windows 10 now.

(autosize and resizable had no effect in Ubuntu, perhaps a quirk with Linux or the properties work with `prefwindow`s but not `dialog`)

**Comment by 117649** [comment]
Tried this?
https://github.com/onemen/TabMixPlus/blob/41b7f3360e3b58b863e91a8ef06bf5f14eb8e718/addon/chrome/content/preferences/preferences.js#L781-L783

**Comment by p1usminus** [comment]
> Tried this? [onemen/TabMixPlus@`41b7f33`/addon/chrome/content/preferences/preferences.js#L781-L783](https://github.com/onemen/TabMixPlus/blob/41b7f3360e3b58b863e91a8ef06bf5f14eb8e718/addon/chrome/content/preferences/preferences.js#L781-L783)
> 
> ```js
> window.requestAnimationFrame(() => {
>       window.sizeToContent();//or maybe just this is enough
>     });
> ```

This did not work, unfortunately. The log output in the onLoad function always showed a window width of 1 when opening options, like the browser could not get the width of the dialog content (and so it cannot resize.) Maybe it works for prefwindow but not dialog?

So I made a new branch to experiment with the resizeBy and resizeTo functions and I have been trying things for the last few days 😰 

I think the issue is caused by padding _again_. There is padding around the TabBox which makes the 'content' for the options wider than the window for the dialog box, but the padding is not included when the width is calculated.

I found I could prevent the issue by setting padding-left/right to 0 with a style attribute for the dialog - maybe I could use this method.

But instead I used resizeTo in the same way as sizeToContent is used in TMP. The JavaScript feels like a less elegant method than using the style attribute, but perhaps it would work better with custom themes.

**Comment by p1usminus** [comment]
> 
> I think the issue is caused by padding _again_. There is padding around the TabBox which makes the 'content' for the options wider than the window for the dialog box, but the padding is not included when the width is calculated.
> 

Keeping a screenshot here - TabBox with grey background, dialog with red background and enlarged horizontal padding

![Screenshot from 2023-05-28 23-31-20](https://github.com/p1usminus/roomybookmarksredux/assets/50540305/2f1ef5ce-cb0b-4390-8fd5-bc5400020dff)
