### ISSUE TITLE
Colour menu alternative options

### ISSUE THREAD

**Issue by p1usminus** [p1usminus/roomybookmarksredux#3]
Quick ideas to replace the functions of the colour menu that seem to be working, inspired by [this](https://superuser.com/a/1312154) post. These will go in your userChrome.css file.

To change the background colour of a bookmark toolbar item:
`#personal-bookmarks .bookmark-item[label="BOOKMARK_NAME"] {
	background: COLOUR !important;
}`

To change the text colour of a bookmark toolbar item:
`#personal-bookmarks .bookmark-item[label="BOOKMARK_NAME"] > .toolbarbutton-text {
	color: COLOUR !important;
}`

Certainly these could be extended to include fancier styling.

An example:
![colourmenualt](https://user-images.githubusercontent.com/50540305/57648636-f323f700-75bd-11e9-83aa-b1c3fe0a92fd.png)

**Comment by p1usminus** [comment]
I think this is one of the instances where it would be far simpler to leave this to userChrome.css than try to fix the colour menu functions in overlay.js (I already tried, ha) so I'll just leave this here for now.

I vaguely remember openColorMenu only partially working, so maybe some of the methods in PlacesUtils have been removed or changed and I didn't catch them all.

**Comment by 117649** [comment]
#7 Got it working some how.
Note:

1. Try not to publish this so fast there is a lot space for improvement.
2. Now we can get guid for every bookmark both on tool bar or not and we even can query where it actually are.
3. So we can have a more precision control on color of each bookmark item.
4. Sqlite api isn't very responsive and feel clunky now better to change it.
5. I've changed css relative code so the background color apply to FavIcon to thus it useful while text is hidden.
6. We should better use guid to form a style sheet for color preferences and update it instead apply color with hardcode Javascript.
