### ISSUE TITLE
bookmarks toobar does not show on hover over bookmarks toolbar while hiding bookmarks bar is enabled

### ISSUE THREAD

**Issue by 117649** [p1usminus/roomybookmarksredux#4]
The result is bookmarks bar would gone while you move mouse cursor from nav bar in to it if you enable aut-hide.
However the bookmarks bar would remain if the cursor is hover on bookmark item in the bookmarks bar.

Using latest waterfox current 2020.06.

**Comment by 117649** [comment]
Oh I see the problem here event listener is not properly triggered on the toolbar itself but can only triggered on item inside toolbar. If it not on a item it just not gonna catch what is there it feel like there is a veil blocking access to the toolbar layer. So weird.

**Comment by p1usminus** [comment]
3 years later (sorry!)

I also noticed some strange behaviour with the auto-hide feature, but this was related to bookmark folders (see video) - I am not sure if this is related or another issue, but it's minor anyway. I could not trigger this issue using the navigation bar, at least with the newest versions - did your changes to overlay.js fix this? 😄

https://user-images.githubusercontent.com/50540305/107562370-a4165600-6bd7-11eb-9e2d-22753236e13f.mp4

**Comment by 117649** [comment]
> 3 years later (sorry!)
> 
> I also noticed some strange behaviour with the auto-hide feature, but this was related to bookmark folders (see video) - I am not sure if this is related or another issue, but it's minor anyway. I could not trigger this issue using the navigation bar, at least with the newest versions - did your changes to overlay.js fix this? 😄
> 
>  roomy.mp4

I'm not sure.
Are you using the version I've modified?
I've changed hidden mechanic thus the hiding triggers when cursor moving away from the listening area. If you move cursor towards an area that would show bookmark bar the bar remain open. This should result a more consistent behavior of hide.

**Comment by 117649** [comment]
#5
