### ISSUE TITLE
My Firefox Developer Edition 87.0b5 is not loading bootstrap addons right

### ISSUE THREAD

**Issue by 117649** [p1usminus/roomybookmarksredux#6]
I'm trying use multiple bootstrap addons and found that browser startup have a big chance been interrupt and hangs especially when having more than one addons enabled and restore a session. (most of the UI are loaded but not the tabs, tool bar button's menu, booksmark bar items)
I'm using script loader for addons.
And Tab Groups just not been loaded while browser start.
Are you seeing any of this?

Addons:
[roomybookmarksredux](https://github.com/p1usminus/roomybookmarksredux/commit/70bd876dd2065d529e669b9a71da3e87f91e3205)
[TMP](https://github.com/onemen/TabMixPlus/tree/rewrite/main)
[Tab-Groups](https://github.com/117649/Tab-Groups)

**Comment by p1usminus** [comment]
I think userChromeJS loads things earlier (than bootstrapLoader) which may affect how the addons interact with the browser.

When I first used userChromeJS instead of bootstrapLoader to use Roomy, the bookmark bar would be blank on startup when I used autohide. I basically just added a delay to one of the startup functions, and I think it helped: https://github.com/p1usminus/roomybookmarksredux/blob/master/src/content/overlay.js#L526

>And some addon just not been loaded while browser start.
For this you may need to clear the startup cache in about:support ([step 6](https://github.com/p1usminus/roomybookmarksredux/blob/master/src/content/overlay.js#L526))

**Comment by p1usminus** [comment]
Roomy + Tab Groups are working okay for me

**Comment by 117649** [comment]
> When I first used userChromeJS instead of bootstrapLoader to use Roomy, the bookmark bar would be blank on startup when I used autohide. I basically just added a delay to one of the startup functions, and I think it helped: https://github.com/p1usminus/roomybookmarksredux/blob/master/src/content/overlay.js#L526

That is one symptom but problem here is browser stuck at the place and loading just pending forever. Yes you do can use anything that is already loaded and even force load some thing but no further loading. 

> For this you may need to clear the startup cache in about:support ([step 6](https://github.com/p1usminus/roomybookmarksredux/blob/master/src/content/overlay.js#L526))

I've tried that but no use.

**Comment by 117649** [comment]
> Roomy + Tab Groups are working okay for me

![image](https://user-images.githubusercontent.com/8281345/109778625-ff1ff380-7c3f-11eb-8412-d40021b58839.png)
If Tab Groups is loaded this guy should appear.

My problem here is Tab Groups not loaded at browser start but if I disable it then re-enable it it can work.

**Comment by p1usminus** [comment]
It loads as expected on browser restart

![image](https://user-images.githubusercontent.com/50540305/109779521-f1497e80-7bfd-11eb-9d1d-573e5633b6e2.png)

Hmm. Maybe try installing userChromeJS again?

**Comment by 117649** [comment]
What FF version you are using?

**Comment by p1usminus** [comment]
Also Firefox Developer Edition, it just updated to 87.0b5

**Comment by 117649** [comment]
Roomy + TMP seems to be the reason.

**Comment by p1usminus** [comment]
That is weird! I have just installed TMP 0.5.8.1 and it is working fine with Roomy (which I just updated again)

**Comment by 117649** [comment]
https://github.com/onemen/TabMixPlus/issues/35#issuecomment-791212742
Fixed here.

But here I also encourage you to try out this new TMP and see if there is anything you like or find any issue.
