### ISSUE TITLE
timeOutHide keeps increasing

### ISSUE THREAD

**Issue by p1usminus** [p1usminus/roomybookmarksredux#9]
This is old and does not seem to affect function, but I cannot work out why it's happening! It seems to increase a little after each hide event.

![image](https://user-images.githubusercontent.com/50540305/111378090-5179ff00-8699-11eb-844b-82cc1596c3f3.png)

**Comment by p1usminus** [comment]
https://github.com/p1usminus/roomybookmarksredux/commit/89302d4f88a735858f0651d049ed214e0d86ec97

With this tiny change I think it increases by smaller amounts each time, but it is still increasing. There may be a difference between browsers too...

![image](https://user-images.githubusercontent.com/50540305/111378760-2f34b100-869a-11eb-880f-931cf54763f4.png)

**Comment by 117649** [comment]
https://www.w3schools.com/jsref/met_win_settimeout.asp

Return Value: | A Number, representing the ID value of the timer that is set. Use this value with the clearTimeout() method to cancel the timer
-- | --

I think as you keep creating new timer it is not surprised the id value goes up......

**Comment by p1usminus** [comment]
lol 🤦 , I thought it was a timer variable like hideBarTime

okay so it's not a problem, good
